name: Build and Publish Nuget Package

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    uses: ${{ github.repository_owner }}/common-workspace-hub/.github/workflows/reusable-publish-nuget.yml@main
    with:
      working-directory: ./src/lib  
      package-source: 'https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json'
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

